final List<Map<String, String>> mockData = [
  {
    "city": "Lagos",
    "lat": "6.4550",
    "lng": "3.3841",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "16637000",
    "population_proper": "16637000"
  },
  {
    "city": "Kano",
    "lat": "12.0000",
    "lng": "8.5167",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Kano",
    "capital": "admin",
    "population": "3848885",
    "population_proper": "3848885"
  },
  {
    "city": "Abuja",
    "lat": "9.0667",
    "lng": "7.4833",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Federal Capital Territory",
    "capital": "primary",
    "population": "3770000",
    "population_proper": "107169"
  },
  {
    "city": "Ibadan",
    "lat": "7.3964",
    "lng": "3.9167",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Oyo",
    "capital": "admin",
    "population": "3552000",
    "population_proper": "2550593"
  },
  {
    "city": "Port Harcourt",
    "lat": "4.8242",
    "lng": "7.0336",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "admin",
    "population": "1865000",
    "population_proper": "1005904"
  },
  {
    "city": "Aba",
    "lat": "5.1167",
    "lng": "7.3667",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Abia",
    "capital": "minor",
    "population": "1530000",
    "population_proper": "1160000"
  },
  {
    "city": "Onitsha",
    "lat": "6.1667",
    "lng": "6.7833",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "1483000",
    "population_proper": "1483000"
  },
  {
    "city": "Maiduguri",
    "lat": "11.8333",
    "lng": "13.1500",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Borno",
    "capital": "admin",
    "population": "1197497",
    "population_proper": "1197497"
  },
  {
    "city": "Benin City",
    "lat": "6.3333",
    "lng": "5.6222",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Edo",
    "capital": "admin",
    "population": "1147188",
    "population_proper": "1147188"
  },
  {
    "city": "Shagamu",
    "lat": "6.8333",
    "lng": "3.6500",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Ogun",
    "capital": "minor",
    "population": "1132270",
    "population_proper": "1132270"
  },
  {
    "city": "Ikare",
    "lat": "7.5167",
    "lng": "5.7500",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Ondo",
    "capital": "minor",
    "population": "1099931",
    "population_proper": "1099931"
  },
  {
    "city": "Ogbomoso",
    "lat": "8.1333",
    "lng": "4.2500",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Oyo",
    "capital": "minor",
    "population": "1032000",
    "population_proper": "1032000"
  },
  {
    "city": "Owerri",
    "lat": "5.4833",
    "lng": "7.0333",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "admin",
    "population": "908109",
    "population_proper": "908109"
  },
  {
    "city": "Ikeja",
    "lat": "6.6186",
    "lng": "3.3426",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "admin",
    "population": "861300",
    "population_proper": "861300"
  },
  {
    "city": "Osogbo",
    "lat": "7.7667",
    "lng": "4.5667",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Osun",
    "capital": "admin",
    "population": "731000",
    "population_proper": "731000"
  },
  {
    "city": "Agege",
    "lat": "6.6219",
    "lng": "3.3258",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "459939",
    "population_proper": "459939"
  },
  {
    "city": "Sokoto",
    "lat": "13.0622",
    "lng": "5.2339",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Sokoto",
    "capital": "admin",
    "population": "427760",
    "population_proper": "427760"
  },
  {
    "city": "Somolu",
    "lat": "6.5408",
    "lng": "3.3872",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "403569",
    "population_proper": "403569"
  },
  {
    "city": "Nnewi",
    "lat": "6.0167",
    "lng": "6.9167",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "391227",
    "population_proper": "391227"
  },
  {
    "city": "Ilesa",
    "lat": "7.6167",
    "lng": "4.7167",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Osun",
    "capital": "minor",
    "population": "384334",
    "population_proper": "384334"
  },
  {
    "city": "Minna",
    "lat": "9.6139",
    "lng": "6.5569",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Niger",
    "capital": "admin",
    "population": "322163",
    "population_proper": "322163"
  },
  {
    "city": "Apapa",
    "lat": "6.4500",
    "lng": "3.3667",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "217362",
    "population_proper": "217362"
  },
  {
    "city": "Bida",
    "lat": "9.0804",
    "lng": "6.0100",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Niger",
    "capital": "minor",
    "population": "173849",
    "population_proper": "173849"
  },
  {
    "city": "Ilobu",
    "lat": "7.8400",
    "lng": "4.4860",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Osun",
    "capital": "minor",
    "population": "118097",
    "population_proper": "118097"
  },
  {
    "city": "Ajegunle",
    "lat": "6.4406",
    "lng": "3.3515",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Oshodi",
    "lat": "6.5550",
    "lng": "3.3436",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ifako",
    "lat": "6.6442",
    "lng": "3.3249",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Surulere",
    "lat": "6.5015",
    "lng": "3.3581",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Mushin",
    "lat": "6.5333",
    "lng": "3.3500",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ebute-Metta",
    "lat": "6.4722",
    "lng": "3.3806",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ojota",
    "lat": "6.5781",
    "lng": "3.3869",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ikotun",
    "lat": "6.5443",
    "lng": "3.2638",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Makera",
    "lat": "10.4714",
    "lng": "7.4103",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Kaduna",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Umundugba",
    "lat": "5.6760",
    "lng": "7.0718",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ojo",
    "lat": "6.4612",
    "lng": "3.1647",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Okrika",
    "lat": "4.7400",
    "lng": "7.0830",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Uselu",
    "lat": "6.3843",
    "lng": "5.6098",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Edo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Kpor",
    "lat": "4.6526",
    "lng": "7.2840",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Neni",
    "lat": "6.0951",
    "lng": "7.0243",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ozubulu",
    "lat": "5.9500",
    "lng": "6.8333",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Festac Town",
    "lat": "6.4697",
    "lng": "3.2830",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Buguma",
    "lat": "4.7333",
    "lng": "6.8667",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Hadejia",
    "lat": "12.4349",
    "lng": "10.0527",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Jigawa",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Amaigbo",
    "lat": "5.7302",
    "lng": "7.1151",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ungogo",
    "lat": "12.0917",
    "lng": "8.4953",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Kano",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ikoyi",
    "lat": "6.4525",
    "lng": "3.4358",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Lagos",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Effurun",
    "lat": "5.5563",
    "lng": "5.7846",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Delta",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Dikenafai",
    "lat": "5.7701",
    "lng": "7.1547",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Kumbotso",
    "lat": "11.8900",
    "lng": "8.5030",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Kano",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Nnenasa",
    "lat": "5.7326",
    "lng": "7.0136",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ojoto",
    "lat": "6.0584",
    "lng": "6.8612",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Rumuodomaya",
    "lat": "4.8933",
    "lng": "7.0023",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Itu",
    "lat": "5.4640",
    "lng": "7.3310",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Afor-Oru",
    "lat": "5.5411",
    "lng": "7.2684",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Isinweke",
    "lat": "5.6205",
    "lng": "7.3499",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Imo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ogu",
    "lat": "4.7225",
    "lng": "7.1986",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Nchia",
    "lat": "4.7931",
    "lng": "7.1206",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Rivers",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Egbeda",
    "lat": "7.3772",
    "lng": "4.0498",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Oyo",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Ukpo",
    "lat": "6.2141",
    "lng": "6.9666",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Abagana",
    "lat": "6.1833",
    "lng": "6.9833",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Anambra",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  },
  {
    "city": "Suleja",
    "lat": "9.1806",
    "lng": "7.1794",
    "country": "Nigeria",
    "iso2": "NG",
    "admin_name": "Niger",
    "capital": "minor",
    "population": "",
    "population_proper": ""
  }
];
